### ISSUE TITLE
running system tools with cwl-tes

### ISSUE THREAD

**Issue by gunjanhariani** [common-workflow-language/cwl-tes#24]
Hi,

I have a step within my cwl pipeline that refers to a cwl that calls a step (primer removal cwl).

  primer_removal:
    in:
      bamfile:
        source: sam2bam/output
        primerfile: primerfile
        out_prefix: sample
    out: [ptrim_file,stats_file1,stats_file2]
    run: ../../CWL_Pipelines/cwltools/removePrimerSeq.cwl

Within my primer-removal cwl, I call the main script in the following manner:
baseCommand: [perl, /ea/scripts/removePrimerSeqFromSAM.6.pl]

So it is not a docker pull.

When I run the pipeline with cwl-tes, I get the following error:
Executor_Error: 
Can't open perl script "/ea/scripts/removePrimerSeqFromSAM.6.pl": No such file or directory

I tried running with --preserve-entire-environment but that did not resolve the issue.

Do you have any suggestions on how to run this with cwl-tes?

Thanks!
Gunjan

**Comment by adamstruck** [comment]
_cwl-tes_ requires all steps to be run within a docker container.  The [TES API](https://github.com/ga4gh/task-execution-schemas) defines its tasks in terms of a docker container.  This makes each step portable across compute infrastructures since the dependencies are packaged into the container. 

If you are running things locally, you could just use _cwltool_.

**Comment by gunjanhariani** [comment]
got it, thank you Adam.
